### ISSUE TITLE
Implement feedback from Tommy

### ISSUE THREAD

**Issue by alex5imon** [KanoComputing/kano-profile#62]
- [x] XP bar says %, should say XX xp
- [x] Filled part of XP Bar should be #ff842a #61
- [ ] Scroll isn’t styled #51
- [ ] When in Badges the XP Bar is not filled
- [x] Bump down sub headers 2px in size
- [x] Increase opacity on Badge description sidebar, contrast between text and colour too low
- [x] Stats bar does not include what it should;  
  [Blocks used] [Hours Spent] [Shares] [% completion] [Graph or progress]
- [x] Lower the opacity of locked Badges to 20%
- [x] Link to profile overview should be styled inactive when in other tabs #52
- [x] Decrease margin between navigation links
- [x] Margin on locked / unlocked status
- [x] Make “Avatars” the first and default tab in Swag
- [x] Bump down Close icon 3px
- [ ] Add border radius to window
